import { Box, Stack, Button,InputLabel, MenuItem, 
    Grid, TextField,
    Skeleton, Typography, Autocomplete } from "@mui/material";
import React, { useState } from "react";
import Post from "./Post";
import Select, { SelectChangeEvent } from '@mui/material/Select';

const Profile = () => {
    const [buttonText, setButtonText] = useState("Edit");
    const [contentEditing, setContentEditing] = useState(false);
    var personalInfo = {
            email: "matthewwang@gmail.com",
            username: "matthewwang",
            identity: "Student",
            school: "The University of Hong Kong",
            grduationYear: "2022",
            graduationMonth: "08",
            company: "Amazon", 
            YoE: "2 years"
        };

    const [userIdentity, setUserIdentity] = useState(personalInfo.identity);

    const handleIdentityChange = (event) => {
        setUserIdentity(event.target.value);
      };


    const handleChange = (event) => {
        event.preventDefault();
        if(contentEditing === false) {
            setButtonText("Save");
            setContentEditing(true);
            
        }
        else{
            setButtonText("Edit");
            setContentEditing(false);
        }

        
    };

  return (
    <Box fullHeight flex={7} p={{ xs: 0, md: 2 }} >
        <Box margin={5} 
            sx = {{
                display: 'flex',
                flexDirection: 'column'
            }}>

            <Box spacing={2}
                sx = {{
                    display: 'flex',
                    flexDirection: 'row'
                }}>
                <Typography variant="h4" fontWeight={100}>
                    Profile Setting
                </Typography>
                <Button onClick = {handleChange} variant="outlined" size="small" sx = {{ml: 4}}>
                    {buttonText}
                </Button>
                
            </Box>

            <Box component="form" noValidate sx={{ mt: 3 }}>
                <Grid container spacing={2}>
                    <Grid item xs={7}>
                        <Typography variant="h6">
                            Email Address
                        </Typography>
                        <TextField
                            disabled
                            fullWidth
                            id="email"
                            label= {personalInfo.email}
                            name="email"
                        />
                    </Grid>

                <Grid item xs={7}>
                    <Typography variant="h6">
                        Username
                    </Typography>
                    <TextField
                        disabled = {!contentEditing}
                        fullWidth
                        id="username"
                        label = {personalInfo.username}
                        name="username"
                    />
                </Grid>
                <Grid item xs={3}></Grid>

                <Grid item xs={4}>
                    <Typography variant="h6">
                        Identity
                    </Typography>

                    <Select
                        labelId="identity"
                        id ="identity"
                        fullWidth
                        value = {userIdentity}
                        label ="identity"
                        disabled = {!contentEditing}
                        onChange={handleIdentityChange}
                    >
                        <MenuItem value = {"Student"}>Student</MenuItem>
                        <MenuItem value = {"Graduated"}>Graduated</MenuItem>
                    </Select>
                </Grid>
                <Grid item xs={8}></Grid>


                <Grid item xs={5}>
                    <Typography variant="h6">
                        Education
                    </Typography>
                    <Autocomplete 
                        disabled = {!contentEditing}
                        id="combo-box-demo"
                        options={topUniversities}
                        renderInput={(params) => <TextField {...params} label="University" />}
                    />
                    
                </Grid>

                <Grid item xs={2}>
                    <Typography variant="h6">
                        Graduation Year
                    </Typography>

                    <TextField
                        disabled = {!contentEditing}
                        fullWidth
                        id="username"
                        label= {personalInfo.grduationYear + "/" + personalInfo.graduationMonth}
                        name="username"
                    />
                </Grid>
                <Grid item xs={5}> </Grid>

                <Grid item xs={5}>
                    <Typography variant="h6">
                        Experience
                    </Typography>

                    <TextField
                        disabled = {!contentEditing}
                        fullWidth
                        id="username"
                        label={personalInfo.company}
                        name="username"
                    />
                </Grid>

                <Grid item xs={2}>
                    <Typography variant="h6">
                        YoE
                    </Typography>

                    <TextField
                        disabled = {!contentEditing}
                        fullWidth
                        id="username"
                        label={personalInfo.YoE}
                        name="username"
                    />
                </Grid>
                </Grid>
                
                
            </Box>
            



        </Box>

    </Box>
  );
};


const topUniversities = [
    {label: 'California Institute of Technology', country: 'United States of America'},
    {label: 'University of Oxford', country: 'United Kingdom'},
    {label: 'Stanford University', country: 'United States of America'},
    {label: 'University of Cambridge', country: 'United Kingdom'},
    {label: 'Massachusetts Institute of Technology', country: 'United States of America'},
    {label: 'Harvard University', country: 'United States of America'},
    {label: 'Princeton University', country: 'United States of America'},
    {label: 'Imperial College London', country: 'United Kingdom'},
    {label: 'ETH Zurich – Swiss Federal Institute of Technology Zurich', country: 'Switzerland'},
    {label: 'University of Chicago', country: 'United States of America'},
    {label: 'Johns Hopkins University', country: 'United States of America'},
    {label: 'Yale University', country: 'United States of America'},
    {label: 'University of California, Berkeley', country: 'United States of America'},
    {label: 'University College London', country: 'United Kingdom'},
    {label: 'Columbia University', country: 'United States of America'},
    {label: 'University of California, Los Angeles', country: 'United States of America'},
    {label: 'University of Pennsylvania', country: 'United States of America'},
    {label: 'Cornell University', country: 'United States of America'},
    {label: 'University of Toronto', country: 'Canada'},
    {label: 'Duke University', country: 'United States of America'},
    {label: 'University of Michigan', country: 'United States of America'},
    {label: 'Carnegie Mellon University', country: 'United States of America'},
    {label: 'London School of Economics and Political Science', country: 'United Kingdom'},
    {label: 'University of Edinburgh', country: 'United Kingdom'},
    {label: 'Northwestern University', country: 'United States of America'},
    {label: 'National University of Singapore', country: 'Singapore'},
    {label: 'King’s College London', country: 'United Kingdom'},
    {label: 'Karolinska Institute', country: 'Sweden'},
    {label: 'LMU Munich', country: 'Germany'},
    {label: 'New York University', country: 'United States of America'},
    {label: 'École Polytechnique Fédérale de Lausanne', country: 'Switzerland'},
    {label: 'University of Washington', country: 'United States of America'},
    {label: 'University of Melbourne', country: 'Australia'},
    {label: 'University of British Columbia', country: 'Canada'},
    {label: 'KU Leuven', country: 'Belgium'},
    {label: 'University of Illinois at Urbana-Champaign', country: 'United States of America'},
    {label: 'Heidelberg University', country: 'Germany'},
    {label: 'McGill University', country: 'Canada'},
    {label: 'University of California, San Diego', country: 'United States of America'},
    {label: 'University of California, Santa Barbara', country: 'United States of America'},
    {label: 'Georgia Institute of Technology', country: 'United States of America'},
    {label: 'Peking University', country: 'China'},
    {label: 'University of Tokyo', country: 'Japan'},
    {label: 'University of California, Davis', country: 'United States of America'},
    {label: 'University of Hong Kong', country: 'Hong Kong'},
    {label: 'University of Texas at Austin', country: 'United States of America'},
    {label: 'Tsinghua University', country: 'China'},
    {label: 'Wageningen University and Research Center', country: 'Netherlands'},
    {label: 'Humboldt University of Berlin', country: 'Germany'},
    {label: 'University of Wisconsin-Madison', country: 'United States of America'},
    {label: 'Brown University', country: 'United States of America'},
    {label: 'Australian National University', country: 'Australia'},
    {label: 'Technical University of Munich', country: 'Germany'},
    {label: 'École Normale Supérieure', country: 'France'},
    {label: 'Nanyang Technological University', country: 'Singapore'},
    {label: 'University of Manchester', country: 'United Kingdom'},
    {label: 'University of Sydney', country: 'Australia'},
    {label: 'University of Amsterdam', country: 'Netherlands'},
    {label: 'Hong Kong University of Science and Technology', country: 'Hong Kong'},
    {label: 'The University of Queensland', country: 'Australia'},
    {label: 'Washington University in St Louis', country: 'United States of America'},
    {label: 'Utrecht University', country: 'Netherlands'},
    {label: 'University of North Carolina at Chapel Hill', country: 'United States of America'},
    {label: 'Boston University', country: 'United States of America'},
    {label: 'Delft University of Technology', country: 'Netherlands'},
    {label: 'University of Minnesota', country: 'United States of America'},
    {label: 'Leiden University', country: 'Netherlands'},
    {label: 'University of Southern California', country: 'United States of America'},
    {label: 'University of Bristol', country: 'United Kingdom'},
    {label: 'Durham University', country: 'United Kingdom'},
    {label: 'Erasmus University Rotterdam', country: 'Netherlands'},
    {label: 'Free University of Berlin', country: 'Germany'},
    {label: 'Monash University', country: 'Australia'},
    {label: 'University of Groningen', country: 'Netherlands'},
    {label: 'Pennsylvania State University', country: 'United States of America'},
    {label: 'University of Glasgow', country: 'United Kingdom'},
    {label: 'University of Helsinki', country: 'Finland'},
    {label: 'University of Tübingen', country: 'Germany'},
    {label: 'University of Pittsburgh', country: 'United States of America'},
    {label: 'University of Warwick', country: 'United Kingdom'},
    {label: 'Uppsala University', country: 'Sweden'},
    {label: 'University of Copenhagen', country: 'Denmark'},
    {label: 'University of New South Wales', country: 'Australia'},
    {label: 'University of Freiburg', country: 'Germany'},
    {label: 'Seoul National University', country: 'South Korea'},
    {label: 'University of St Andrews', country: 'United Kingdom'},
    {label: 'Vanderbilt University', country: 'United States of America'},
    {label: 'Kyoto University', country: 'Japan'},
    {label: 'Maastricht University', country: 'Netherlands'},
    {label: 'Emory University', country: 'United States of America'},
    {label: 'Lund University', country: 'Sweden'},
    {label: 'Ohio State University', country: 'United States of America'},
    {label: 'University of Exeter', country: 'United Kingdom'},
    {label: 'University of Bonn', country: 'Germany'},
    {label: 'Georgetown University', country: 'United States of America'},
    {label: 'McMaster University', country: 'Canada'},
    {label: 'University of Sheffield', country: 'United Kingdom'},
    {label: 'Queen Mary University of London', country: 'United Kingdom'},
    {label: 'University of Göttingen', country: 'Germany'},
    {label: 'Michigan State University', country: 'United States of America'},
    {label: 'University of Basel', country: 'Switzerland'},
    {label: 'École Polytechnique', country: 'France'},
    {label: 'Rice University', country: 'United States of America'},
    {label: 'Dartmouth College', country: 'United States of America'},
    {label: 'University of Zurich', country: 'Switzerland'},
    {label: 'Aarhus University', country: 'Denmark'},
    {label: 'University of California, Irvine', country: 'United States of America'},
    {label: 'University of Mannheim', country: 'Germany'},
    {label: 'University of Notre Dame', country: 'United States of America'},
    {label: 'University of Western Australia', country: 'Australia'},
    {label: 'RWTH Aachen University', country: 'Germany'},
    {label: 'University of Southampton', country: 'United Kingdom'},
    {label: 'Scuola Normale Superiore di Pisa', country: 'Italy'},
    {label: 'University of Montreal', country: 'Canada'},
    {label: 'Pierre and Marie Curie University', country: 'France'},
    {label: 'Purdue University', country: 'United States of America'},
    {label: 'Pohang University of Science and Technology', country: 'South Korea'},
    {label: 'University of Maryland, College Park', country: 'United States of America'},
    {label: 'Ghent University', country: 'Belgium'},
    {label: 'University of Birmingham', country: 'United Kingdom'},
    {label: 'University of Bern', country: 'Switzerland'},
    {label: 'University of Cape Town', country: 'South Africa'},
    {label: 'University of Florida', country: 'United States of America'},
    {label: 'University of Erlangen-Nuremberg', country: 'Germany'},
    {label: 'Rutgers, the State University of New Jersey', country: 'United States of America'},
    {label: 'University of Münster', country: 'Germany'},
    {label: 'Radboud University Nijmegen', country: 'Netherlands'},
    {label: 'University of Colorado Boulder', country: 'United States of America'},
    {label: 'Tufts University', country: 'United States of America'},
    {label: 'Royal Holloway, University of London', country: 'United Kingdom'},
    {label: 'Lancaster University', country: 'United Kingdom'},
    {label: 'University of Geneva', country: 'Switzerland'},
    {label: 'University of York', country: 'United Kingdom'},
    {label: 'Case Western Reserve University', country: 'United States of America'},
    {label: 'University of Leeds', country: 'United Kingdom'},
    {label: 'University of Oslo', country: 'Norway'},
    {label: 'Stockholm University', country: 'Sweden'},
    {label: 'University of Alberta', country: 'Canada'},
    {label: 'Chinese University of Hong Kong', country: 'Hong Kong'},
    {label: 'Karlsruhe Institute of Technology', country: 'Germany'},
    {label: 'University of Sussex', country: 'United Kingdom'},
    {label: 'University of Massachusetts', country: 'United States of America'},
    {label: 'University of Vienna', country: 'Austria'},
    {label: 'University of Nottingham', country: 'United Kingdom'},
    {label: 'University of California, Santa Cruz', country: 'United States of America'},
    {label: 'University of Lausanne', country: 'Switzerland'},
    {label: 'Autonomous University of Barcelona', country: 'Spain'},
    {label: 'University of Virginia', country: 'United States of America'},
    {label: 'Korea Advanced Institute of Science and Technology (KAIST)', country: 'South Korea'},
    {label: 'University of Adelaide', country: 'Australia'},
    {label: 'University of East Anglia', country: 'United Kingdom'},
    {label: 'University of Twente', country: 'Netherlands'},
    {label: 'Sungkyunkwan University (SKKU)', country: 'South Korea'},
    {label: 'VU University Amsterdam', country: 'Netherlands'},
    {label: 'KTH Royal Institute of Technology', country: 'Sweden'},
    {label: 'University of Cologne', country: 'Germany'},
    {label: 'University of Liverpool', country: 'United Kingdom'},
    {label: 'TU Dresden', country: 'Germany'},
    {label: 'University of Rochester', country: 'United States of America'},
    {label: 'Trinity College Dublin', country: 'Republic of Ireland'},
    {label: 'Lomonosov Moscow State University', country: 'Russian Federation'},
    {label: 'University of Miami', country: 'United States of America'},
    {label: 'University of Arizona', country: 'United States of America'},
    {label: 'Pompeu Fabra University', country: 'Spain'},
    {label: 'University of Reading', country: 'United Kingdom'},
    {label: 'Yeshiva University', country: 'United States of America'},
    {label: 'University of California, Riverside', country: 'United States of America'},
    {label: 'University of Leicester', country: 'United Kingdom'},
    {label: 'National Taiwan University', country: 'Taiwan'},
    {label: 'Technical University of Denmark', country: 'Denmark'},
    {label: 'Université Catholique de Louvain', country: 'Belgium'},
    {label: 'University of Aberdeen', country: 'United Kingdom'},
    {label: 'University of Auckland', country: 'New Zealand'},
    {label: 'University of Barcelona', country: 'Spain'},
    {label: 'University of Konstanz', country: 'Germany'},
    {label: 'Eindhoven University of Technology', country: 'Netherlands'},
    {label: 'University College Dublin', country: 'Republic of Ireland'},
    {label: 'Hebrew University of Jerusalem', country: 'Israel'},
    {label: 'University of Waterloo', country: 'Canada'},
    {label: 'University of Gothenburg', country: 'Sweden'},
    {label: 'Scuola Superiore Sant’Anna', country: 'Italy'},
    {label: 'University of Bergen', country: 'Norway'},
    {label: 'Cardiff University', country: 'United Kingdom'},
    {label: 'University of Utah', country: 'United States of America'},
    {label: 'Brandeis University', country: 'United States of America'},
    {label: 'University of Dundee', country: 'United Kingdom'},
    {label: 'University of Würzburg', country: 'Germany'},
    {label: 'Paris-Sud University', country: 'France'},
    {label: 'Arizona State University', country: 'United States of America'},
    {label: 'University of Antwerp', country: 'Belgium'},
    {label: 'Boston College', country: 'United States of America'},
    {label: 'Ulm University', country: 'Germany'},
    {label: 'University of Luxembourg', country: 'Luxembourg'},
    {label: 'Texas A&M University', country: 'United States of America'},
    {label: 'Charité - Universitätsmedizin Berlin', country: 'Germany'},
    {label: 'Newcastle University', country: 'United Kingdom'},
    {label: 'St George’s, University of London', country: 'United Kingdom'},
    {label: 'University of Trento', country: 'Italy'},
    {label: 'Paris Diderot University – Paris 7', country: 'France'},
    {label: 'Queen’s University Belfast', country: 'United Kingdom'},
    {label: 'Aalborg University', country: 'Denmark'},
    {label: 'Birkbeck, University of London', country: 'United Kingdom'},
    {label: 'University of Bologna', country: 'Italy'},
    {label: 'University at Buffalo', country: 'United States of America'},
    {label: 'University of Calgary', country: 'Canada'},
    {label: 'Chalmers University of Technology', country: 'Sweden'},
    {label: 'City University of Hong Kong', country: 'Hong Kong'},
    {label: 'Copenhagen Business School', country: 'Denmark'},
    {label: 'Dalhousie University', country: 'Canada'},
    {label: 'University of Duisburg-Essen', country: 'Germany'},
    {label: 'École Normale Supérieure de Lyon', country: 'France'},
    {label: 'Florida State University', country: 'United States of America'},
    {label: 'University of Fribourg', country: 'Switzerland'},
    {label: 'Fudan University', country: 'China'},
    {label: 'George Washington University', country: 'United States of America'},
    {label: 'Goethe University Frankfurt', country: 'Germany'},
    {label: 'University of Hawai’i at Mānoa', country: 'Unisted States of America'},
    {label: 'Hong Kong Polytechnic University', country: 'Hong Kong'},
    {label: 'University of Illinois at Chicago', country: 'United States of America'},
    {label: 'Indiana University', country: 'United States of America'},
    {label: 'University of Iowa', country: 'United States of America'},
    {label: 'Johannes Gutenberg University of Mainz', country: 'Germany'},
    {label: 'Joseph Fourier University', country: 'France'},
    {label: 'University of Kiel', country: 'Germany'},
    {label: 'Laval University', country: 'Canada'},
    {label: 'Medical University of Vienna', country: 'Austria'},
    {label: 'Northeastern University', country: 'United States of America'},
    {label: 'Oregon Health and Science University', country: 'United States of America'},
    {label: 'University of Otago', country: 'New Zealand'},
    {label: 'University of Ottawa', country: 'Canada'},
    {label: 'Paris Descartes University', country: 'France'},
    {label: 'Peter the Great St Petersburg Polytechnic University', country: 'Russian Federation'},
    {label: 'Polytechnic University of Milan', country: 'Italy'},
    {label: 'Royal Veterinary College', country: 'United Kingdom'},
    {label: 'Rush University', country: 'United States of America'},
    {label: 'Sapienza University of Rome', country: 'Italy'},
    {label: 'University of Science and Technology of China', country: 'China'},
    {label: 'University of South Florida', country: 'United States of America'},
    {label: 'Stony Brook University', country: 'United States of America'},
    {label: 'University of Stuttgart', country: 'Germany'},
    {label: 'Swedish University of Agricultural Sciences', country: 'Sweden'},
    {label: 'Technical University of Darmstadt', country: 'Germany'},
    {label: 'University of Technology Sydney', country: 'Australia'},
    {label: 'Tel Aviv University', country: 'Israel'},
    {label: 'University of Texas at Dallas', country: 'United States of America'},
    {label: 'Tilburg University', country: 'Netherlands'},
    {label: 'Tohoku University', country: 'Japan'},
    {label: 'Tokyo Institute of Technology', country: 'Japan'},
    {label: 'University of Victoria', country: 'Canada'},
    {label: 'Wake Forest University', country: 'United States of America'},
    {label: 'University of Western Ontario', country: 'Canada'},
    {label: 'William & Mary', country: 'United States of America'},
    {label: 'University of the Witwatersrand', country: 'South Africa'},
    {label: 'Aalto University', country: 'Finland'},
    {label: 'Aix-Marseille University', country: 'France'},
    {label: 'University of Bath', country: 'United Kingdom'},
    {label: 'Bayreuth University', country: 'Germany'},
    {label: 'Bielefeld University', country: 'Germany'},
    {label: 'University of Bordeaux', country: 'France'},
    {label: 'Charles Darwin University', country: 'Australia'},
    {label: 'Colorado School of Mines', country: 'United States of America'},
    {label: 'Colorado State University', country: 'United States of America'},
    {label: 'University of Delaware', country: 'United States of America'},
    {label: 'Flinders University', country: 'Australia'},
    {label: 'University of Georgia', country: 'United States of America'},
    {label: 'Griffith University', country: 'Australia'},
    {label: 'University of Iceland', country: 'Iceland'},
    {label: 'Indian Institute of Science', country: 'India'},
    {label: 'Iowa State University', country: 'United States of America'},
    {label: 'James Cook University', country: 'Australia'},
    {label: 'Justus Liebig University Giessen', country: 'Germany'},
    {label: 'King Abdulaziz University', country: 'Saudi Arabia'},
    {label: 'Koç University', country: 'Turkey'},
    {label: 'Korea University', country: 'South Korea'},
    {label: 'University of Liège', country: 'Belgium'},
    {label: 'Linköping University', country: 'Sweden'},
    {label: 'Nanjing University', country: 'China'},
    {label: 'National Tsing Hua University', country: 'Taiwan'},
    {label: 'National University of Ireland, Galway', country: 'Republic of Ireland'},
    {label: 'University of Newcastle', country: 'Australia'},
    {label: 'North Carolina State University', country: 'United States of America'},
    {label: 'Oregon State University', country: 'United States of America'},
    {label: 'Osaka University', country: 'Japan'},
    {label: 'Queen’s University', country: 'Canada'},
    {label: 'Queensland University of Technology', country: 'Australia'},
    {label: 'Rensselaer Polytechnic Institute', country: 'United States of America'},
    {label: 'Royal College of Surgeons in Ireland', country: 'Republic of Ireland'},
    {label: 'Ruhr University Bochum', country: 'Germany'},
    {label: 'Saint Louis University', country: 'United States of America'},
    {label: 'University of São Paulo', country: 'Brazil'},
    {label: 'Simon Fraser University', country: 'Canada'},
    {label: 'University of Surrey', country: 'United Kingdom'},
    {label: 'Syracuse University', country: 'United States of America'},
    {label: 'University of Tasmania', country: 'Australia'},
    {label: 'University of Tennessee, Knoxville', country: 'United States of America'},
    {label: 'Tomsk Polytechnic University', country: 'Russian Federation'},
    {label: 'Tulane University', country: 'United States of America'},
    {label: 'Umeå University', country: 'Sweden'},
    {label: 'Vienna University of Technology', country: 'Austria'},
    {label: 'Virginia Polytechnic Institute and State University', country: 'United States of America'},
    {label: 'University of Wollongong', country: 'Australia'},
    {label: 'Zhejiang University', country: 'China'},
    {label: 'Aberystwyth University', country: 'United Kingdom'},
    {label: 'University of Alaska Fairbanks', country: 'United States of America'},
    {label: 'Autonomous University of Madrid', country: 'Spain'},
    {label: 'Bangor University', country: 'United Kingdom'},
    {label: 'University of Bremen', country: 'Germany'},
    {label: 'University of Cincinnati', country: 'United States of America'},
    {label: 'University of Connecticut', country: 'United States of America'},
    {label: 'Deakin University', country: 'Australia'},
    {label: 'University of Essex', country: 'United Kingdom'},
    {label: 'George Mason University', country: 'United States of America'},
    {label: 'University of Greifswald', country: 'Germany'},
    {label: 'Gwangju Institute of Science and Technology', country: 'South Korea'},
    {label: 'University of Hohenheim', country: 'Germany'},
    {label: 'University of Innsbruck', country: 'Austria'},
    {label: 'Kazan Federal University', country: 'Russian Federation'},
    {label: 'University of Kent', country: 'United Kingdom'},
    {label: 'Leibniz University of Hanover', country: 'Germany'},
    {label: 'Macquarie University', country: 'Australia'},
    {label: 'Medical College of Wisconsin', country: 'United States of America'},
    {label: 'University of Milan', country: 'Italy'},
    {label: 'University of Milan-Bicocca', country: 'Italy'},
    {label: 'Montpellier University', country: 'France'},
    {label: 'Nagoya University', country: 'Japan'},
    {label: 'University of Naples Federico II', country: 'Italy'},
    {label: 'National Chiao Tung University', country: 'Taiwan'},
    {label: 'National Research Nuclear University MePhI', country: 'Russian Federation'},
    {label: 'National Taiwan University of Science and Technology (Taiwan Tech)', country: 'Taiwan'},
    {label: 'University of Navarra', country: 'Spain'},
    {label: 'University of Nebraska-Lincoln', country: 'United States of America'},
    {label: 'Örebro University', country: 'Sweden'},
    {label: 'University of Oregon', country: 'United States of America'},
    {label: 'University of Padua', country: 'Italy'},
    {label: 'University of Pavia', country: 'Italy'},
    {label: 'Plymouth University', country: 'United Kingdom'},
    {label: 'Shanghai Jiao Tong University', country: 'China'},
    {label: 'University of Southern Denmark', country: 'Denmark'},
    {label: 'Stellenbosch University', country: 'South Africa'},
    {label: 'University of Strasbourg', country: 'France'},
    {label: 'Technical University of Dortmund', country: 'Germany'},
    {label: 'Technion Israel Institute of Technology', country: 'Israel'},
    {label: 'Toulouse 1 Capitole University', country: 'France'},
    {label: 'University of Trieste', country: 'Italy'},
    {label: 'University of Turin', country: 'Italy'},
    {label: 'University of Turku', country: 'Finland'},
    {label: 'Vrije Universiteit Brussel', country: 'Belgium'},
    {label: 'VŠB - Technical University of Ostrava', country: 'Czech Republic'},
    {label: 'Yonsei University', country: 'South Korea'},
    {label: 'York University', country: 'Canada'},
    {label: 'Bilkent University', country: 'Turkey'},
    {label: 'Binghamton University, State University of New York', country: 'United States of America'},
    {label: 'University of Crete', country: 'Greece'},
    {label: 'University of Cyprus', country: 'Cyprus'},
    {label: 'Drexel University', country: 'United States of America'},
    {label: 'University of Eastern Finland', country: 'Finland'},
    {label: 'University of Florence', country: 'Italy'},
    {label: 'University of St Gallen', country: 'Switzerland'},
    {label: 'Graz University of Technology', country: 'Austria'},
    {label: 'University of Guelph', country: 'Canada'},
    {label: 'Hanyang University', country: 'South Korea'},
    {label: 'Hong Kong Baptist University', country: 'Hong Kong'},
    {label: 'University of Houston', country: 'United States of America'},
    {label: 'Indian Institute of Technology Bombay', country: 'India'},
    {label: 'Instituto Superior Técnico Lisboa', country: 'Portugal'},
    {label: 'University of Jyväskylä', country: 'Finland'},
    {label: 'La Trobe University', country: 'Australia'},
    {label: 'Loughborough University', country: 'United Kingdom'},
    {label: 'University of Manitoba', country: 'Canada'},
    {label: 'University of Missouri', country: 'United States of America'},
    {label: 'University of Modena and Reggio Emilia', country: 'Italy'},
    {label: 'University of Montana', country: 'United States of America'},
    {label: 'National University of Ireland, Maynooth', country: 'Republic of Ireland'},
    {label: 'University of Nebraska Medical Center', country: 'United States of America'},
    {label: 'University of New Mexico', country: 'United States of America'},
    {label: 'Norwegian University of Science and Technology', country: 'Norway'},
    {label: 'University of Oulu', country: 'Finland'},
    {label: 'Panthéon-Sorbonne University – Paris 1', country: 'France'},
    {label: 'Polytechnic University of Turin', country: 'Italy'},
    {label: 'University of Rome III', country: 'Italy'},
    {label: 'Sabancı University', country: 'Turkey'},
    {label: 'San Diego State University', country: 'United States of America'},
    {label: 'University of South Australia', country: 'Australia'},
    {label: 'University of South Carolina', country: 'United States of America'},
    {label: 'University of South Dakota', country: 'United States of America'},
    {label: 'State University of Campinas', country: 'Brazil'},
    {label: 'University of Stirling', country: 'United Kingdom'},
    {label: 'Sun Yat-sen University', country: 'China'},
    {label: 'Swansea University', country: 'United Kingdom'},
    {label: 'Swinburne University of Technology', country: 'Australia'},
    {label: 'University of Tartu', country: 'Estonia'},
    {label: 'Temple University', country: 'United States of America'},
    {label: 'University of Texas at San Antonio', country: 'United States of America'},
    {label: 'UiT The Arctic University of Norway', country: 'Norway'},
    {label: 'Université Libre de Bruxelles', country: 'Belgium'},
    {label: 'Lille 2 University – Health and Law', country: 'France'},
    {label: 'University College Cork', country: 'Republic of Ireland'},
    {label: 'Verona University', country: 'Italy'},
    {label: 'Victoria University of Wellington', country: 'New Zealand'},
    {label: 'Washington State University', country: 'United States of America'},
    {label: 'Wayne State University', country: 'United States of America'},
    {label: 'American University', country: 'United States of America'},
    {label: 'Aston University', country: 'Unted Kingdom'},
    {label: 'University of Aveiro', country: 'Portugal'},
    {label: 'University of Bari Aldo Moro', country: 'Italy'},
    {label: 'Bar-Ilan University', country: 'Israel'},
    {label: 'Bournemouth University', country: 'United Kingdom'},
    {label: 'University of Brescia', country: 'Italy'},
    {label: 'Brno University of Technology', country: 'Czech Republic'},
    {label: 'Brunel University London', country: 'United Kingdom'},
    {label: 'Ca’ Foscari University of Venice', country: 'Italy'},
    {label: 'University of Cagliari', country: 'Italy'},
    {label: 'University of Canterbury', country: 'New Zealand'},
    {label: 'Catholic University of the Sacred Heart', country: 'Italy'},
    {label: 'Charles University in Prague', country: 'Czech Republic'},
    {label: 'China Medical University, Taiwan', country: 'Taiwan'},
    {label: 'City University London', country: 'United Kingdom'},
    {label: 'Claude Bernard University Lyon 1', country: 'France'},
    {label: 'University of Coimbra', country: 'Portugal'},
    {label: 'Complutense University of Madrid', country: 'Spain'},
    {label: 'Concordia University', country: 'Canada'},
    {label: 'Curtin University', country: 'Australia'},
    {label: 'Dublin City University', country: 'Republic of Ireland'},
    {label: 'East China University of Science and Technology', country: 'China'},
    {label: 'Ewha Womans University', country: 'South Korea'},
    {label: 'Federico Santa María Technical University', country: 'Chile'},
    {label: 'University of Ferrara', country: 'Italy'},
    {label: 'Florida International University', country: 'United States of America'},
    {label: 'University of Genoa', country: 'Italy'},
    {label: 'Georgia State University', country: 'United States of America'},
    {label: 'University of Graz', country: 'Austria'},
    {label: 'Heriot-Watt University', country: 'United Kingdom'},
    {label: 'Hokkaido University', country: 'Japan'},
    {label: 'Howard University', country: 'United States of America'},
    {label: 'University of Hull', country: 'United Kingdom'},
    {label: 'University of Idaho', country: 'United States of America'},
    {label: 'Indian Institute of Technology Delhi', country: 'India'},
    {label: 'Indian Institute of Technology Kharagpur', country: 'India'},
    {label: 'Indian Institute of Technology Madras', country: 'India'},
    {label: 'University of Ioannina', country: 'Greece'},
    {label: 'Iran University of Science and Technology', country: 'Iran'},
    {label: 'Johannes Kepler University of Linz', country: 'Austria'},
    {label: 'University of Kaiserslautern', country: 'Germany'},
    {label: 'Keele University', country: 'United Kingdom'},
    {label: 'University of KwaZulu-Natal', country: 'South Africa'},
    {label: 'Kyung Hee University', country: 'South Korea'},
    {label: 'Kyushu University', country: 'Japan'},
    {label: 'Lehigh University', country: 'United States of America'},
    {label: 'Louisiana State University', country: 'United States of America'},
    {label: 'University of Macau', country: 'Macau'},
    {label: 'Makerere University', country: 'Uganda'},
    {label: 'Marche Polytechnic University', country: 'Italy'},
    {label: 'University of Maryland, Baltimore County', country: 'United States of America'},
    {label: 'Murdoch University', country: 'Australia'},
    {label: 'University of Nantes', country: 'France'},
    {label: 'National and Kapodistrian University of Athens', country: 'Greece'},
    {label: 'National Autonomous University of Mexico', country: 'Mexico'},
    {label: 'National Cheng Kung University', country: 'Taiwan'},
    {label: 'National Institute of Applied Sciences of Lyon (INSA Lyon)', country: 'France'},
    {label: 'National Yang-Ming University', country: 'Taiwan'},
    {label: 'University of Neuchâtel', country: 'Switzerland'},
    {label: 'New University of Lisbon', country: 'Portugal'},
    {label: 'University of Nice Sophia Antipolis', country: 'France'},
    {label: 'Novosibirsk State University', country: 'Russian Federation'},
    {label: 'The Open University', country: 'United Kingdom'},
    {label: 'Oxford Brookes University', country: 'United Kingdom'},
    {label: 'University of Palermo', country: 'Italy'},
    {label: 'University of Parma', country: 'Italy'},
    {label: 'University of Pisa', country: 'Italy'},
    {label: 'Polytechnic University of Catalonia', country: 'Spain'},
    {label: 'Pontifical Catholic University of Chile', country: 'Chile'},
    {label: 'University of Porto', country: 'Portugal'},
    {label: 'University of Portsmouth', country: 'United Kingdom'},
    {label: 'RMIT University', country: 'Australia'},
    {label: 'University of Rome II – Tor Vergata', country: 'Italy'},
    {label: 'University of Rovira i Virgili', country: 'Spain'},
    {label: 'Saint Petersburg State University', country: 'Russian Federation'},
    {label: 'University of Salento', country: 'Italy'},
    {label: 'University of San Francisco', country: 'United States of America'},
    {label: 'University of Saskatchewan', country: 'Canada'},
    {label: 'Sharif University of Technology', country: 'Iran'},
    {label: 'University of Siena', country: 'Italy'},
    {label: 'Southern Cross University', country: 'Australia'},
    {label: 'State University of New York Albany', country: 'United States of America'},
    {label: 'University of Strathclyde', country: 'United Kingdom'},
    {label: 'University of Tampere', country: 'Finland'},
    {label: 'Tampere University of Technology', country: 'Finland'},
    {label: 'Tokyo Medical and Dental University (TMDU)', country: 'Japan'},
    {label: 'Tokyo Metropolitan University', country: 'Japan'},
    {label: 'University of Tsukuba', country: 'Japan'},
    {label: 'University of Ulsan', country: 'South Korea'},
    {label: 'Ulster University', country: 'United Kingdom'},
    {label: 'Université du Québec à Montréal', country: 'Canada'},
    {label: 'Universiti Teknologi Malaysia', country: 'Malaysia'},
    {label: 'University of Urbino Carlo Bo', country: 'Italy'},
    {label: 'University of Valencia', country: 'Spain'},
    {label: 'University of Waikato', country: 'New Zealand'},
    {label: 'Western Sydney University', country: 'Australia'},
    {label: 'Wuhan University', country: 'China'},
    {label: 'Xiamen University', country: 'China'},
    {label: 'American University of Beirut', country: 'Lebanon'},
    {label: 'Amirkabir University of Technology', country: 'Iran'},
    {label: 'University of the Andes, Colombia', country: 'Colombia'},
    {label: 'University of Arkansas', country: 'United States of America'},
    {label: 'Auburn University', country: 'United States of America'},
    {label: 'Babeş-Bolyai University', country: 'Romania'},
    {label: 'University of the Basque Country', country: 'Spain'},
    {label: 'Bauman Moscow State Technical University', country: 'Russian Federation'},
    {label: 'Ben-Gurion University of the Negev', country: 'Israel'},
    {label: 'Blaise Pascal University', country: 'France'},
    {label: 'Boğaziçi University', country: 'Turkey'},
    {label: 'University of Burgundy', country: 'France'},
    {label: 'University of Canberra', country: 'Australia'},
    {label: 'Carleton University', country: 'Canada'},
    {label: 'University of Catania', country: 'Italy'},
    {label: 'Central Queensland University', country: 'Australia'},
    {label: 'University of Chile', country: 'Chile'},
    {label: 'China Agricultural University', country: 'China'},
    {label: 'Chung-Ang University', country: 'South Korea'},
    {label: 'Czech Technical University in Prague', country: 'Czech Republic'},
    {label: 'De Montfort University', country: 'United Kingdom'},
    {label: 'East China Normal University', country: 'China'},
    {label: 'Edith Cowan University', country: 'Australia'},
    {label: 'Federal University of Rio de Janeiro', country: 'Brazil'},
    {label: 'University of Granada', country: 'Spain'},
    {label: 'University of Haifa', country: 'Israel'},
    {label: 'Harbin Institute of Technology', country: 'China'},
    {label: 'University of Hertfordshire', country: 'United Kingdom'},
    {label: 'Hiroshima University', country: 'Japan'},
    {label: 'Huazhong University of Science and Technology', country: 'China'},
    {label: 'Indian Institute of Technology Guwahati', country: 'India'},
    {label: 'Indian Institute of Technology Kanpur', country: 'India'},
    {label: 'Indian Institute of Technology Roorkee', country: 'India'},
    {label: 'Isfahan University of Technology', country: 'Iran'},
    {label: 'Istanbul Technical University', country: 'Turkey'},
    {label: 'Jadavpur University', country: 'India'},
    {label: 'Kanazawa University', country: 'Japan'},
    {label: 'Kansas State University', country: 'United States of America'},
    {label: 'Keio University', country: 'Japan'},
    {label: 'Kent State University', country: 'United States of America'},
    {label: 'King Fahd University of Petroleum and Minerals', country: 'Saudi Arabia'},
    {label: 'King Saud University', country: 'Saudi Arabia'},
    {label: 'University of La Laguna', country: 'Spain'},
    {label: 'Lappeenranta University of Technology', country: 'Finland'},
    {label: 'University of Limerick', country: 'Republic of Ireland'},
    {label: 'University of Lisbon', country: 'Portugal'},
    {label: 'Liverpool John Moores University', country: 'United Kingdom'},
    {label: 'Mahidol University', country: 'Thailand'},
    {label: 'Manchester Metropolitan University', country: 'United Kingdom'},
    {label: 'University of Maribor', country: 'Slovenia'},
    {label: 'Masaryk University', country: 'Czech Republic'},
    {label: 'Massey University', country: 'New Zealand'},
    {label: 'Memorial University of Newfoundland', country: 'Canada'},
    {label: 'Middle East Technical University', country: 'Turkey'},
    {label: 'University of Minho', country: 'Portugal'},
    {label: 'Missouri University of Science and Technology', country: 'United States of America'},
    {label: 'Montana State University', country: 'United States of America'},
    {label: 'Monterrey Institute of Technology and Higher Education', country: 'Mexico'},
    {label: 'National Central University', country: 'Taiwan'},
    {label: 'National Sun Yat-Sen University', country: 'Taiwan'},
    {label: 'National Taiwan Normal University', country: 'Taiwan'},
    {label: 'National Technical University of Athens', country: 'Greece'},
    {label: 'New Jersey Institute of Technology', country: 'United States of America'},
    {label: 'New Mexico State University', country: 'United States of America'},
    {label: 'University of North Carolina at Greensboro', country: 'United States of America'},
    {label: 'Oklahoma State University', country: 'United States of America'},
    {label: 'Osaka City University', country: 'Japan'},
    {label: 'Otto von Guericke University of Magdeburg', country: 'Germany'},
    {label: 'University of Oviedo', country: 'Spain'},
    {label: 'Palacký University in Olomouc', country: 'Czech Republic'},
    {label: 'Panjab University', country: 'India'},
    {label: 'Paris Dauphine University', country: 'France'},
    {label: 'Pontifical Catholic University of Rio de Janeiro (PUC-Rio)', country: 'Brazil'},
    {label: 'Portland State University', country: 'United States of America'},
    {label: 'University of Pretoria', country: 'South Africa'},
    {label: 'Pusan National University', country: 'South Korea'},
    {label: 'Quaid-i-azam University', country: 'Pakistan'},
    {label: 'University of Regina', country: 'Canada'},
    {label: 'Renmin University of China', country: 'China'},
    {label: 'University of Rennes 1', country: 'France'},
    {label: 'University of Salamanca', country: 'Spain'},
    {label: 'University of Santiago de Compostela', country: 'Spain'},
    {label: 'Semmelweis University', country: 'Hungary'},
    {label: 'University of Seville', country: 'Spain'},
    {label: 'Université de Sherbrooke', country: 'Canada'},
    {label: 'Soochow University', country: 'China'},
    {label: 'South China University of Technology', country: 'China'},
    {label: 'Tallinn University of Technology', country: 'Estonia'},
    {label: 'Tehran University of Medical Sciences', country: 'Iran'},
    {label: 'University of Texas at Arlington', country: 'United States of America'},
    {label: 'Tianjin University', country: 'China'},
    {label: 'Tokyo University of Agriculture and Technology', country: 'Japan'},
    {label: 'University of Toledo', country: 'United States of America'},
    {label: 'Tongji University', country: 'China'},
    {label: 'University of Tulsa', country: 'United States of America'},
    {label: 'United Arab Emirates University', country: 'United Arab Emirates'},
    {label: 'University of Warsaw', country: 'Poland'},
    {label: 'University of Wisconsin-Milwaukee', country: 'United States of America'},
    {label: 'Xi’an Jiaotong University', country: 'China'},
    {label: 'University of Zaragoza', country: 'Spain'},
    {label: 'University of A Coruña', country: 'Spain'},
    {label: 'Adam Mickiewicz University', country: 'Poland'},
    {label: 'AGH University of Science and Technology', country: 'Poland'},
    {label: 'Ajou University', country: 'South Korea'},
    {label: 'University of Alcalá', country: 'Spain'},
    {label: 'Alexandria University', country: 'Egypt'},
    {label: 'Alexandru Ioan Cuza University', country: 'Romania'},
    {label: 'Aligarh Muslim University', country: 'India'},
    {label: 'American University of Sharjah', country: 'United Arab Emirates'},
    {label: 'Amrita University', country: 'India'},
    {label: 'Anadolu University', country: 'Turkey'},
    {label: 'Andhra University', country: 'India'},
    {label: 'University of Antioquia', country: 'Colombia'},
    {label: 'Aristotle University of Thessaloniki', country: 'Greece'},
    {label: 'Asia University, Taiwan', country: 'Taiwan'},
    {label: 'Athens University of Economics and Business', country: 'Greece'},
    {label: 'Auckland University of Technology', country: 'New Zealand'},
    {label: 'Austral University of Chile', country: 'Chile'},
    {label: 'Beijing Institute of Technology', country: 'China'},
    {label: 'Belarusian State University', country: 'Belarus'},
    {label: 'University of Belgrade', country: 'Serbia'},
    {label: 'Birla Institute of Technology and Science, Pilani', country: 'India'},
    {label: 'University of Bradford', country: 'United Kingdom'},
    {label: 'University of Brasília', country: 'Brazil'},
    {label: 'University of Brighton', country: 'United Kingdom'},
    {label: 'University of Bucharest', country: 'Romania'},
    {label: 'Budapest University of Technology and Economics', country: 'Hungary'},
    {label: 'Cairo University', country: 'Egypt'},
    {label: 'University of Calcutta', country: 'India'},
    {label: 'California State University, Long Beach', country: 'United States of America'},
    {label: 'Capital Medical University', country: 'China'},
    {label: 'University of Castilla-La Mancha', country: 'Spain'},
    {label: 'University of Central Lancashire', country: 'United Kingdom'},
    {label: 'University of Cergy-Pontoise', country: 'France'},
    {label: 'Chang Gung University', country: 'Taiwan'},
    {label: 'Carlos III University of Madrid', country: 'Spain'},
    {label: 'University of Chemistry and Technology, Prague', country: 'Czech Republic'},
    {label: 'Chiang Mai University', country: 'Thailand'},
    {label: 'Chiba University', country: 'Japan'},
    {label: 'China University of Geosciences (Wuhan)', country: 'China'},
    {label: 'China University of Petroleum (Beijing)', country: 'China'},
    {label: 'Chonbuk National University', country: 'South Korea'},
    {label: 'Chongqing University', country: 'China'},
    {label: 'Chonnam National University', country: 'South Korea'},
    {label: 'Chulalongkorn University', country: 'Thailand'},
    {label: 'Chung Yuan Christian University', country: 'Taiwan'},
    {label: 'Chungnam National University', country: 'South Korea'},
    {label: 'Clemson University', country: 'United States of America'},
    {label: 'Comenius University in Bratislava', country: 'Slovakia'},
    {label: 'Coventry University', country: 'United Kingdom'},
    {label: 'Dalian University of Technology', country: 'China'},
    {label: 'University of Debrecen', country: 'Hungary'},
    {label: 'University of Delhi', country: 'India'},
    {label: 'University of Dhaka', country: 'Bangladesh'},
    {label: 'Dublin Institute of Technology', country: 'Republic of Ireland'},
    {label: 'Ehime University', country: 'Japan'},
    {label: 'University of Electronic Science and Technology of China', country: 'China'},
    {label: 'Eötvös Loránd University', country: 'Hungary'},
    {label: 'Erciyes University', country: 'Turkey'},
    {label: 'Federal University of Bahia', country: 'Brazil'},
    {label: 'Federal University of Minas Gerais', country: 'Brazil'},
    {label: 'Federal University of Paraná (UFPR)', country: 'Brazil'},
    {label: 'Federal University of Rio Grande do Sul', country: 'Brazil'},
    {label: 'Federal University of Santa Catarina', country: 'Brazil'},
    {label: 'Federal University of São Carlos', country: 'Brazil'},
    {label: 'Federal University of Viçosa', country: 'Brazil'},
    {label: 'Federal University of Lavras', country: 'Brazil'},
    {label: 'Feng Chia University', country: 'Taiwan'},
    {label: 'Florida Institute of Technology', country: 'United States of America'},
    {label: 'Fu Jen Catholic University', country: 'Taiwan'},
    {label: 'Gdańsk University of Technology', country: 'Poland'},
    {label: 'University of Ghana', country: 'Ghana'},
    {label: 'Gifu University', country: 'Japan'},
    {label: 'Glasgow Caledonian University', country: 'United Kingdom'},
    {label: 'University of Greenwich', country: 'United Kingdom'},
    {label: 'Hacettepe University', country: 'Turkey'},
    {label: 'University of Huddersfield', country: 'United Kingdom'},
    {label: 'Hunan University', country: 'China'},
    {label: 'University of Ibadan', country: 'Nigeria'},
    {label: 'University of Indonesia', country: 'Indonesia'},
    {label: 'Inha University', country: 'South Korea'},
    {label: 'I-Shou University', country: 'Taiwan'},
    {label: 'Istanbul University', country: 'Turkey'},
    {label: 'Jagiellonian University', country: 'Poland'},
    {label: 'Jilin University', country: 'China'},
    {label: 'University of Jordan', country: 'Jordan'},
    {label: 'Jordan University of Science and Technology', country: 'Jordan'},
    {label: 'Juntendo University', country: 'Japan'},
    {label: 'K.N. Toosi University of Technology', country: 'Iran'},
    {label: 'Kaohsiung Medical University', country: 'Taiwan'},
    {label: 'Khon Kaen University', country: 'Thailand'},
    {label: 'King Mongkut’s University of Technology Thonburi', country: 'Thailand'},
    {label: 'Kingston University', country: 'United Kingdom'},
    {label: 'Kinki University', country: 'Japan'},
    {label: 'Kobe University', country: 'Japan'},
    {label: 'Konkuk University', country: 'South Korea'},
    {label: 'Kumamoto University', country: 'Japan'},
    {label: 'Kyungpook National University', country: 'South Korea'},
    {label: 'Kyushu Institute of Technology', country: 'Japan'},
    {label: 'University of Latvia', country: 'Latvia'},
    {label: 'Lille 1 University – Science and Technology', country: 'France'},
    {label: 'University of Lincoln', country: 'United Kingdom'},
    {label: 'University of Ljubljana', country: 'Slovenia'},
    {label: 'University of Marrakech Cadi Ayyad', country: 'Morocco'},
    {label: 'Miami University', country: 'United States of America'},
    {label: 'Middlesex University', country: 'United Kingdom'},
    {label: 'Moscow Institute of Physics and Technology', country: 'Russian Federation'},
    {label: 'University of Murcia', country: 'Spain'},
    {label: 'Nagasaki University', country: 'Japan'},
    {label: 'University of Nairobi', country: 'Kenya'},
    {label: 'National Chengchi University', country: 'Taiwan'},
    {label: 'National Chung Cheng University', country: 'Taiwan'},
    {label: 'National Chung Hsing University', country: 'Taiwan'},
    {label: 'National Taipei University of Technology', country: 'Taiwan'},
    {label: 'National Taiwan Ocean University', country: 'Taiwan'},
    {label: 'National University of Córdoba', country: 'Argentina'},
    {label: 'National University of Science and Technology (MISiS)', country: 'Russian Federation'},
    {label: 'National University of Sciences and Technology', country: 'Pakistan'},
    {label: 'Niigata University', country: 'Japan'},
    {label: 'Northumbria University', country: 'United Kingdom'},
    {label: 'Northwestern Polytechnical University', country: 'China'},
    {label: 'Nottingham Trent University', country: 'United Kingdom'},
    {label: 'Oakland University', country: 'United States of America'},
    {label: 'Ocean University of China', country: 'China'},
    {label: 'Ohio University', country: 'United States of America'},
    {label: 'Okayama University', country: 'Japan'},
    {label: 'Osaka Prefecture University', country: 'Japan'},
    {label: 'University of Pardubice', country: 'Czech Republic'},
    {label: 'University of Paris North – Paris 13', country: 'France'},
    {label: 'Paris-Sorbonne University – Paris 4', country: 'France'},
    {label: 'University of Patras', country: 'Greece'},
    {label: 'University of Pécs', country: 'Hungary'},
    {label: 'Polytechnic University of Valencia', country: 'Spain'},
    {label: 'Pontifical Catholic University of Paraná', country: 'Brazil'},
    {label: 'Pontifical Catholic University of Rio Grande do Sul (PUCRS)', country: 'Brazil'},
    {label: 'Pontifical Catholic University of Valparaíso', country: 'Chile'},
    {label: 'Prince of Songkla University', country: 'Thailand'},
    {label: 'Qatar University', country: 'Qatar'},
    {label: 'Rio de Janeiro State University (UERJ)', country: 'Brazil'},
    {label: 'Rochester Institute of Technology', country: 'United States of America'},
    {label: 'Saitama University', country: 'Japan'},
    {label: 'University of Salford', country: 'United Kingdom'},
    {label: 'University of Santiago, Chile (USACH)', country: 'Chile'},
    {label: 'São Paulo State University (UNESP)', country: 'Brazil'},
    {label: 'Savitribai Phule Pune University', country: 'India'},
    {label: 'University of Science and Technology Beijing', country: 'China'},
    {label: 'Sejong University', country: 'South Korea'},
    {label: 'University of Seoul', country: 'South Korea'},
    {label: 'Shahid Beheshti University', country: 'Iran'},
    {label: 'Shanghai University', country: 'China'},
    {label: 'Shantou University', country: 'China'},
    {label: 'Sheffield Hallam University', country: 'United Kingdom'},
    {label: 'Shinshu University', country: 'Japan'},
    {label: 'Showa University', country: 'Japan'},
    {label: 'Sichuan University', country: 'China'},
    {label: 'University of Silesia in Katowice', country: 'Poland'},
    {label: 'Slovak University of Technology in Bratislava', country: 'Slovakia'},
    {label: 'Sogang University', country: 'South Korea'},
    {label: 'Sophia University', country: 'Japan'},
    {label: 'University of South Africa', country: 'South Africa'},
    {label: 'Southern Federal University', country: 'Russian Federation'},
    {label: 'University of Southern Mississippi', country: 'United States of America'},
    {label: 'University of Southern Queensland', country: 'Australia'},
    {label: 'Suez Canal University', country: 'Egypt'},
    {label: 'Sultan Qaboos University', country: 'Oman'},
    {label: 'Suranaree University of Technology', country: 'Thailand'},
    {label: 'University of Szeged', country: 'Hungary'},
    {label: 'Taipei Medical University', country: 'Taiwan'},
    {label: 'Taras Shevchenko National University of Kyiv', country: 'Ukraine'},
    {label: 'Technical University of Madrid', country: 'Spain'},
    {label: 'University of Tehran', country: 'Iran'},
    {label: 'University of Texas at El Paso', country: 'United States of America'},
    {label: 'Texas Tech University', country: 'United States of America'},
    {label: 'Tokai University', country: 'Japan'},
    {label: 'Tokushima University', country: 'Japan'},
    {label: 'Tokyo University of Marine Science and Technology', country: 'Japan'},
    {label: 'Tokyo University of Science', country: 'Japan'},
    {label: 'Tomsk State University', country: 'Russian Federation'},
    {label: 'Tottori University', country: 'Japan'},
    {label: 'Toyohashi University of Technology', country: 'Japan'},
    {label: 'Universiti Kebangsaan Malaysia', country: 'Malaysia'},
    {label: 'Universiti Putra Malaysia', country: 'Malaysia'},
    {label: 'Universiti Sains Malaysia', country: 'Malaysia'},
    {label: 'Universiti Teknologi MARA', country: 'Malaysia'},
    {label: 'Ural Federal University', country: 'Russian Federation'},
    {label: 'V.N. Karazin Kharkiv National University', country: 'Ukraine'},
    {label: 'University of Vigo', country: 'Spain'},
    {label: 'Vilnius University', country: 'Lithuania'},
    {label: 'Warsaw University of Technology', country: 'Poland'},
    {label: 'Waseda University', country: 'Japan'},
    {label: 'University of West Bohemia', country: 'Czech Republic'},
    {label: 'University of the West of England', country: 'United Kingdom'},
    {label: 'West University of Timişoara', country: 'Romania'},
    {label: 'University of Westminster', country: 'United Kingdom'},
    {label: 'Xidian University', country: 'China'},
    {label: 'Yeungnam University', country: 'South Korea'},
    {label: 'Yıldız Technical University', country: 'Turkey'},
    {label: 'Yokohama City University', country: 'Japan'},
    {label: 'Yokohama National University', country: 'Japan'},
    {label: 'Yuan Ze University', country: 'Taiwan'}

];

export default Profile;
